env: local

logger:
  environment: "dev"
  service_name: "webhook_service"
  level: debug
  encoding: json
  disable_stacktrace: true

database:
  address: 0.0.0.0:3308
  user: app_user
  passwd: pwd123
  allow_native_passwords: true
  database_name: webhook
  max_open_conn: 10
  max_idle_conn: 5
  conn_max_life_time: 10m

redis_connection:
  addr: 0.0.0.0:6379
  db: 0
  pool_size: 10

kafka_subscriber_event:
#  brokers: 0.0.0.0:29091,0.0.0.0:29092,0.0.0.0:29093
  brokers: 0.0.0.0:9092
  topic: "flodesk.account.subscriber_event"
  auto_commit: true
  client_id: "flodesk.webhook"
  consumer_group: "flodesk.webhook.subscriber_event.notify_event"

dead_letter_producer:
#  brokers: 0.0.0.0:29091,0.0.0.0:29092,0.0.0.0:29093
  brokers: 0.0.0.0:9092
  topic: "flodesk.dead_letter"
  client_id: "flodesk"

temporal:
  host: localhost:7233
  namespace: flodesk
  task_queue: webhook
  enable_tls: false
  enable_encoder: true
  enable_compress: true

http_client:
  timeout: 30s