{
 "title": "Kafka Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentile", "label": "percentile", "query": "90,95,99" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Consume Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_handle_duration_seconds_count[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag Consume Message",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum by(topic, group, le) (rate(kafka_lag_consume_duration_seconds_bucket[1m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consume Latency Message",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum by(topic, le) (rate(kafka_consumer_handle_duration_seconds_bucket[1m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_handle_duration_seconds_count{status!=\"OK\"}[1m])) by (topic, status)",
     "legendFormat": "{{topic}}-{{status}}"
    }
   ]
  },
  {
   "title": "Memory-Thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory $service_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes + process_resident_memory_bytes)by (pod)",
     "legendFormat": "{{pod}}-Total"
    }
   ]
  },
  {
   "title": "Goroutines $service_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(go_goroutines) by (pod)", "legendFormat": "{{pod}}-Goroutines" }
   ]
  },
  {
   "title": "CPU Usage $service_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}